### ISSUE TITLE
Asterisk auf Win7 Rechner

### ISSUE THREAD

**Issue by bahnuhr** [schmupu/ioBroker.asterisk#10]
Hallo,
im Text steht:
Automatische Erstellung der Asterisk Konfiguration
Gehe auf den Reiter "Asterisk Settings" und aktiviere das Kontrollkästchen "Anlegen der Asterisk Konfigurationsdateien (einmalig)". Drücke anschließend auf „Speichern und Schließen". Nun befinden sich die Konfigurationsdateien im /tmp/ Verzeichnis. Kopiere diese wie unten beschrieben das Verzeichnis /etc/asterisk. Die Benutzerberechtigungen der Dateien im /etc/asterisk Verzeichnis müssen unverändert bleiben. Vielleicht müssen die Berechtigungen nach dem Kopieren angepasst werden.

Wenn man dies auf einem Win7 Rechner installieren will; wo muss man dann die o.g. Dateien hin kopieren ?

mfg

**Comment by schmupu** [comment]
Ich habe leider keine Windows Rechner, nur Linux und Mac :-( Gibt es ein Asterisk Verzeichnis bzw. Unterverzeichnis wo die sip.conf, manager.conf, ... liegen? Ggf. musst Du im Explorer einmal nach den Dateien suchen. Da kopierst Du dann die Dateien hin.
