### ISSUE TITLE
CPH Last von 23% auf 120%

### ISSUE THREAD

**Issue by LJSven** [schmupu/ioBroker.asterisk#2]
Wenn ich den Adapter aktiviere geht mein Raspberry 3B ziemlich in die Knie - im Schnitt habe ich eine CPH Auslastung von 23% / wenn ich den Adapter aktiviere bin ich bei 120%
Hast du da eine Idee?

**Comment by schmupu** [comment]
>Wenn ich den Adapter aktiviere geht mein Raspberry 3B ziemlich in die Knie - im Schnitt habe ich eine CPH Auslastung von 23% / wenn ich den Adapter aktiviere bin ich bei 120% ...

@LJSven 

Moin, wie ist es, wenn Asterix auf dem Raspberry läuft aber der Asterisk Adapter deaktiviert ist? Ist die CPU Last immer noch hoch? Ich werde das gleich einmal auf meiner NAS auch anschauen.

Ich habe gestern Abend eine neue Version erstellt. Dafür musst du die /etc/asterisk/super.conf anoasseb. Dort muss [iobroker] an einer Stelle stehen.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LJSven** [comment]
Dann ist die CPH Last runter. 
![bildschirmfoto 2018-11-13 um 07 34 49](https://user-images.githubusercontent.com/8560588/48395209-cda15800-e716-11e8-979f-eb80ef6ff1b7.png)

**Comment by schmupu** [comment]
>Dann ist die CPH Last runter.  ...

@LJSven , du musst mir helfen wo sieht die Last im Screenshot? Ich schaue mir die Last immer mit uptime, procinfo oder top an.
Der ioBroker Asterisk Adapter baut einmalig eine Verbindung zum Asterisk Manager auf. Die wird bisher nicht abgebaut. Ich kann versuchen ob ich nach einem Call einen Verbindungsabau initiierte. Weiß aber nicht was mit den asynchronen calls passiert. 
Und ich habe noch eine Idee, die du vielleicht gleich testen kannst.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LJSven** [comment]
Uptime ohne Adapter
08:16:33 up 20:52,  1 user,  load average: 0,72, 0,84, 0,71
Uptime mit Adapter
08:18:44 up 20:54,  1 user,  load average: 1,50, 1,04, 0,79

TOP
top - 08:19:22 up 20:55,  1 user,  load average: 1,67, 1,14, 0,84
Tasks: 113 total,   2 running,  69 sleeping,   0 stopped,   0 zombie
%Cpu(s): 22,4 us,  4,1 sy,  0,0 ni, 72,5 id,  0,0 wa,  0,0 hi,  1,0 si,  0,0 st
KiB Mem :   949452 total,   149636 free,   679480 used,   120336 buff/cache
KiB Swap:   102396 total,    36092 free,    66304 used.   219184 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                      
23250 root      20   0  147820  63868  17380 R  99,0  6,7   1:51.73 io.asterisk.0                                                
  522 root      20   0  183680  80236  10196 S   3,0  8,5 131:29.15 iobroker.js-con                                              
  631 root      20   0  183560  68256  12340 S   2,3  7,2  38:25.86 io.javascript.0                                              
23312 root      20   0    8512   3196   2756 R   1,3  0,3   0:00.46 top                                                          
   19 root      20   0       0      0      0 S   1,0  0,0   0:06.28 ksoftirqd/2                                                  
  497 asterisk  20   0  240880   7840    764 S   1,0  0,8  11:13.63 asterisk                                                     
   68 root      20   0       0      0      0 S   0,3  0,0   0:57.79 mmcqd/0                                                      
  609 root      20   0  123852  21000   8664 S   0,3  2,2   0:42.71 io.geofency.0                                                
  653 root      20   0  122580  23360   9396 S   0,3  2,5   0:58.82 io.mihome.0                                                  
  732 root      20   0  161496  53992   8372 S   0,3  5,7  10:47.96 io.sonoff.0                                                  
  862 root      20   0  139792  42768  11452 S   0,3  4,5   5:11.52 io.radar.0                                                   
 8936 root      20   0  132612  33472  12064 S   0,3  3,5   0:47.21 io.alexa2.0                                                  
12586 root      20   0  128072  31792  11024 S   0,3  3,3   1:03.73 io.shelly.0                                                  
23193 root      20   0   11528   5792   5060 S   0,3  0,6   0:00.50 sshd                                                         
    1 root      20   0   27060   4408   3596 S   0,0  0,5   0:04.10 systemd                                                      
    2 root      20   0       0      0      0 S   0,0  0,0   0:00.05 kthreadd

**Comment by schmupu** [comment]
Okay, load average ist höher aber noch nicht grenzwertig.  Ich bin dabei , es so zu programmieren, das die Verbindung nach einem Call abgebaut wird. Mal sehen ob das hilft. Hat aber den Nachteil, das man Asterisk Events nicht abfragen kann

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schmupu** [comment]
kleine Anpassungen vorgenommen. Hoffentlich hiflt es
